/**
 * F102 bootstrap — idempotent.
 *
 * Two responsibilities:
 *
 * 1. Ensure every KB has a `/neurons/glossary.md` Neuron. KBs created
 *    before F102 shipped never got one at creation-time.
 *
 * 2. Clean up glossaries that landed with the WRONG seed content. The
 *    first F102 ship (commit 8770194) mis-seeded the Neuron with the
 *    trail-APP terminology (Trail, Neuron, Curator, …) drawn from
 *    data/glossary.json. That's app vocabulary — it lives in the
 *    global /glossary admin panel. Per-KB glossaries are meant for
 *    DOMAIN-specific fagtermer the compile-pipeline harvests from
 *    Sources. This bootstrap detects the polluted content via a
 *    signature marker (see glossary-seed.ts POLLUTED_SEED_MARKERS)
 *    and overwrites it with the empty template via a direct
 *    documents-table UPDATE. A wiki_events row is written so the
 *    rewrite is visible in the history rather than looking like a
 *    silent mutation.
 *
 * Safe to leave in place forever: both the SELECT guard (creates
 *    only when missing) and the content-marker check (rewrites only
 *    still-polluted seeds) idempotent-ize out after one run.
 */
import {
  documents,
  knowledgeBases,
  wikiEvents,
  type TrailDatabase,
} from '@trail/db';
import { and, eq } from 'drizzle-orm';
import { createCandidate } from '@trail/core';
import {
  buildSeedGlossary,
  POLLUTED_SEED_MARKERS,
  POLLUTED_MARKER_THRESHOLD,
} from '../services/glossary-seed.js';
import { backfillGlossaryForKb } from '../services/glossary-backfill.js';

// Content markers the backfill uses to decide "this glossary is an
// empty template and has never been populated" — one per locale,
// drawn from the first line of the seed body.
const EMPTY_TEMPLATE_MARKERS = [
  'Domæne-specifikke fagtermer fra denne vidensbase. Ingen endnu',
  'Domain-specific terms from this knowledge base. None yet',
];

// Content markers that identify AI-populated glossaries (as opposed to
// curator-edited ones). Present only in output of buildGlossaryContent.
// If a glossary has this marker AND is missing the footer marker, it
// was generated by an older backfill version that didn't emit See also
// links — queue it for re-backfill so entries get their Neuron links.
const AI_POPULATED_MARKERS = [
  'Genereret retroaktivt fra eksisterende Neuroner',
  'Generated retroactively from existing Neurons',
];
const FOOTER_MARKERS = ['_Se også:', '_See also:'];

const GLOSSARY_FILENAME = 'glossary.md';
const GLOSSARY_PATH = '/neurons/';

type Kb = {
  id: string;
  tenantId: string;
  createdBy: string;
  name: string;
  language: string | null;
};

export async function seedMissingGlossaryNeurons(trail: TrailDatabase): Promise<void> {
  const kbs = (await trail.db
    .select({
      id: knowledgeBases.id,
      tenantId: knowledgeBases.tenantId,
      createdBy: knowledgeBases.createdBy,
      name: knowledgeBases.name,
      language: knowledgeBases.language,
    })
    .from(knowledgeBases)
    .all()) as Kb[];

  if (kbs.length === 0) return;

  // KBs whose glossary is still the empty template after the seed+
  // cleanup passes — these are the ones the retroactive LLM backfill
  // needs to process. Collected inside the loop, run AFTER boot.
  const needsBackfill: Kb[] = [];

  let seeded = 0;
  let rewritten = 0;
  for (const kb of kbs) {
    const existing = await trail.db
      .select({
        id: documents.id,
        content: documents.content,
        version: documents.version,
      })
      .from(documents)
      .where(
        and(
          eq(documents.knowledgeBaseId, kb.id),
          eq(documents.tenantId, kb.tenantId),
          eq(documents.filename, GLOSSARY_FILENAME),
          eq(documents.path, GLOSSARY_PATH),
          eq(documents.archived, false),
        ),
      )
      .get();

    if (!existing) {
      if (await seedGlossary(trail, kb)) {
        seeded += 1;
        needsBackfill.push(kb);
      }
      continue;
    }

    const content = existing.content ?? '';
    const markerHits = POLLUTED_SEED_MARKERS.filter((m) => content.includes(m)).length;
    const isPolluted = markerHits >= POLLUTED_MARKER_THRESHOLD;
    if (isPolluted) {
      const replacement = buildSeedGlossary(kb.language);
      await rewriteGlossary(trail, kb, existing.id, existing.version, replacement);
      rewritten += 1;
      needsBackfill.push(kb);
      continue;
    }

    // Not polluted, not missing — check three states:
    //   (1) still the empty template → queue initial backfill
    //   (2) AI-populated but missing footer links → queue re-backfill
    //       so entries get their [[neuron-link]] "Se også" footers
    //   (3) curator-edited (neither marker) → leave alone
    const isEmptyTemplate = EMPTY_TEMPLATE_MARKERS.some((m) => content.includes(m));
    const isAiPopulated = AI_POPULATED_MARKERS.some((m) => content.includes(m));
    const hasFooters = FOOTER_MARKERS.some((m) => content.includes(m));
    if (isEmptyTemplate) {
      needsBackfill.push(kb);
    } else if (isAiPopulated && !hasFooters) {
      needsBackfill.push(kb);
    }
  }

  if (seeded > 0) {
    console.log(`  F102 bootstrap: seeded glossary.md in ${seeded} KB(s)`);
  }
  if (rewritten > 0) {
    console.log(`  F102 bootstrap: rewrote polluted glossary in ${rewritten} KB(s) (reverted to empty template)`);
  }

  // Fire-and-forget retroactive backfill. One LLM call per empty KB,
  // serialised so we don't spawn 200 CLI subprocesses at scale. Runs
  // AFTER the async return so engine boot isn't blocked by Haiku
  // latency — subscribers + admin come up immediately; glossaries
  // populate in the background as each KB's pass finishes.
  if (needsBackfill.length > 0) {
    console.log(
      `  F102 bootstrap: queueing retroactive backfill for ${needsBackfill.length} empty glossary(ies) — runs in background`,
    );
    void runBackfillSerial(trail, needsBackfill);
  }
}

/**
 * Sequential backfill loop — one KB at a time. Keeps LLM concurrency
 * at 1 so a 200-KB boot doesn't swamp the CLI lane or the model host.
 * Tolerates per-KB errors without aborting the queue.
 */
async function runBackfillSerial(trail: TrailDatabase, kbs: Kb[]): Promise<void> {
  let totalEntries = 0;
  const t0 = Date.now();
  for (const kb of kbs) {
    try {
      const entries = await backfillGlossaryForKb(trail, kb);
      totalEntries += entries;
    } catch (err) {
      console.error(
        `[F102 backfill] unhandled error for KB "${kb.name}":`,
        err instanceof Error ? err.message : err,
      );
    }
  }
  const elapsed = Math.round((Date.now() - t0) / 1000);
  console.log(
    `[F102 backfill] complete: ${kbs.length} KB(s), ${totalEntries} total entries, ${elapsed}s`,
  );
}

async function seedGlossary(trail: TrailDatabase, kb: Kb): Promise<boolean> {
  const lang = kb.language ?? 'da';
  const title = lang === 'da' ? 'Ordliste' : 'Glossary';
  const content = buildSeedGlossary(lang);

  try {
    await createCandidate(
      trail,
      kb.tenantId,
      {
        knowledgeBaseId: kb.id,
        kind: 'ingest-summary',
        title,
        content,
        metadata: JSON.stringify({
          op: 'create',
          filename: GLOSSARY_FILENAME,
          path: GLOSSARY_PATH,
          source: 'bootstrap:F102',
        }),
        confidence: 1,
      },
      { id: kb.createdBy, kind: 'system' },
    );
    return true;
  } catch (err) {
    console.error(
      `[F102 bootstrap] failed to seed glossary for KB "${kb.name}":`,
      err instanceof Error ? err.message : err,
    );
    return false;
  }
}

async function rewriteGlossary(
  trail: TrailDatabase,
  kb: Kb,
  docId: string,
  currentVersion: number,
  content: string,
): Promise<void> {
  const nextVersion = currentVersion + 1;
  const nowIso = new Date().toISOString();
  try {
    await trail.db
      .update(documents)
      .set({ content, version: nextVersion, updatedAt: nowIso })
      .where(eq(documents.id, docId))
      .run();

    // History trail so the rewrite is auditable rather than a silent
    // mutation. Actor kind 'system' (the bootstrap ran the update, not
    // a human), eventType 'edited' matches the normal rewrite event.
    await trail.db.insert(wikiEvents).values({
      id: crypto.randomUUID(),
      tenantId: kb.tenantId,
      documentId: docId,
      eventType: 'edited',
      actorId: kb.createdBy,
      actorKind: 'system',
      previousVersion: currentVersion,
      newVersion: nextVersion,
      summary: 'F102 bootstrap: replaced polluted glossary seed with empty template',
      contentSnapshot: content,
      createdAt: nowIso,
    }).run();
  } catch (err) {
    console.error(
      `[F102 bootstrap] failed to rewrite polluted glossary for KB "${kb.name}":`,
      err instanceof Error ? err.message : err,
    );
  }
}
