/**
 * Admin i18n — two sides to the problem, one module handles both.
 *
 * 1. **System-level strings** (nav labels, tab names, button text, error
 *    messages we ship in code). These live in locale dicts at
 *    `apps/admin/src/locales/{lang}.json`. Access via `t('key.path')`.
 *
 * 2. **Content-level strings** (action labels + explanations generated by
 *    the LLM at candidate creation, translated on first view). These
 *    arrive as `BilingualText` objects on candidates and are rendered via
 *    `bilingual(text, locale)` — which picks the right language field
 *    with a graceful fallback to English.
 *
 * Locale is stored in `localStorage.trail.admin.lang` so it survives
 * reloads. Initial value comes from `navigator.language` ('da-*' -> 'da',
 * else 'en'). Adding a third locale = drop a JSON file into `locales/` +
 * list it in SUPPORTED_LOCALES — no wiring changes.
 */
import { useEffect, useState } from 'preact/hooks';
import type { BilingualText } from '@trail/shared';
import enDict from '../locales/en.json';
import daDict from '../locales/da.json';

export type Locale = 'en' | 'da';

export const SUPPORTED_LOCALES: ReadonlyArray<{ code: Locale; label: string }> = [
  { code: 'en', label: 'English' },
  { code: 'da', label: 'Dansk' },
];

const DICTS: Record<Locale, Dict> = {
  en: enDict as Dict,
  da: daDict as Dict,
};

type Dict = Record<string, unknown>;

const STORAGE_KEY = 'trail.admin.lang';

function detectInitial(): Locale {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored === 'en' || stored === 'da') return stored;
  } catch {
    // no storage (SSR, sandboxed iframe, etc.)
  }
  if (typeof navigator !== 'undefined' && navigator.language) {
    if (navigator.language.toLowerCase().startsWith('da')) return 'da';
  }
  return 'en';
}

// Global locale state — a tiny pub/sub so any component can subscribe to
// changes without pulling in a full context provider. The useLocale()
// hook below is the ergonomic API.
let currentLocale: Locale = detectInitial();
const listeners = new Set<(locale: Locale) => void>();

export function getLocale(): Locale {
  return currentLocale;
}

export function setLocale(locale: Locale): void {
  if (currentLocale === locale) return;
  currentLocale = locale;
  try {
    localStorage.setItem(STORAGE_KEY, locale);
  } catch {
    // ignore
  }
  document.documentElement.setAttribute('lang', locale);
  for (const fn of listeners) fn(locale);
}

export function useLocale(): Locale {
  const [l, setL] = useState<Locale>(currentLocale);
  useEffect(() => {
    const fn = (next: Locale): void => setL(next);
    listeners.add(fn);
    return () => {
      listeners.delete(fn);
    };
  }, []);
  return l;
}

/**
 * Look up a system string. Dot-path into the locale dict (e.g.
 * `queue.tabs.pending`). Falls back to English when the key is missing
 * from the active locale, and falls back to the raw key when it's missing
 * from English too — that makes unknown keys visible in the UI rather
 * than rendering blank.
 */
export function t(key: string, vars?: Record<string, string | number>): string {
  const raw =
    lookup(DICTS[currentLocale], key) ?? lookup(DICTS.en, key) ?? key;
  if (!vars) return raw;
  return raw.replace(/\{(\w+)\}/g, (_, name: string) =>
    vars[name] !== undefined ? String(vars[name]) : `{${name}}`,
  );
}

function lookup(dict: Dict, path: string): string | null {
  const parts = path.split('.');
  let cur: unknown = dict;
  for (const p of parts) {
    if (cur && typeof cur === 'object' && p in (cur as Dict)) {
      cur = (cur as Dict)[p];
    } else {
      return null;
    }
  }
  return typeof cur === 'string' ? cur : null;
}

/**
 * Pick the right language from a BilingualText. Falls back to English
 * when the requested locale field is missing — the translation service
 * fills those in lazily, so the first view in Danish of a fresh candidate
 * renders English until the async translation lands.
 *
 * Accepts a plain string as an already-translated value. Many legacy
 * candidates (436+ `ingest-page-update` rows as of 2026-04-25) persisted
 * `{ label: "Approve" }` instead of the bilingual struct. Without
 * string-tolerance here, those rows render blank labels — the curator
 * sees empty option-buttons with only the "▼ Hvad betyder det her?"
 * hint below, which looks broken.
 */
export function bilingual(
  text: BilingualText | string | undefined,
  locale?: Locale,
): string {
  if (text === undefined || text === null) return '';
  if (typeof text === 'string') return text;
  const loc = locale ?? currentLocale;
  const specific = (text as Record<string, unknown>)[loc];
  if (typeof specific === 'string' && specific.length > 0) return specific;
  return text.en ?? '';
}

// Set the <html lang="..."> attribute once at startup so screen readers
// and spellcheckers pick the right language immediately.
if (typeof document !== 'undefined') {
  document.documentElement.setAttribute('lang', currentLocale);
}
