/**
 * F15 — Reference extraction.
 *
 * Parses Neuron content after it commits to the wiki and writes rows into
 * `document_references` so the claim-provenance graph stays populated. The
 * schema expects wikiDocumentId → sourceDocumentId pairs ("this Neuron
 * cites that Source"), so this MVP extracts ONLY frontmatter-level source
 * citations:
 *
 *   ---
 *   sources: ["Filename.pdf", "Another.pdf"]
 *   ---
 *
 * That's the exact pattern the ingest prompt tells the compiler to emit on
 * source-summary pages at `/neurons/sources/`, so back-populating against
 * existing Sanne content fills in the missing provenance in one pass.
 *
 * Body-level `[[wiki-link]]` cross-references between Neurons are a
 * separate semantic (navigation, not provenance) and will need a wiki→wiki
 * backlink table rather than reusing document_references. Out of scope
 * for this MVP.
 *
 * Invariant: idempotent. The unique index on (wikiDocumentId,
 * sourceDocumentId, claimAnchor) means re-running against the same content
 * is a no-op. Safe to hook on every candidate_approved + run as a boot
 * sweep.
 */
import { documents, documentReferences, type TrailDatabase } from '@trail/db';
import { and, eq } from 'drizzle-orm';
import type { CandidateApprovedEvent, IngestCompletedEvent } from '@trail/shared';
import { broadcaster } from './broadcast.js';

type WikiDoc = {
  id: string;
  tenantId: string;
  knowledgeBaseId: string;
  filename: string;
  content: string | null;
};

type SourceDoc = {
  id: string;
  filename: string;
};

/**
 * Extract `sources: [...]` from a YAML frontmatter block. Lenient parser —
 * handles array-of-strings in brackets, one-line or multi-line, with or
 * without quotes. Returns canonical filenames trimmed of whitespace.
 *
 * Out of scope: deep YAML parsing. Our frontmatter is generated by our own
 * ingest prompt, so it's predictable. A breaking edge case can be added to
 * the test suite when one shows up.
 */
export function parseFrontmatterSources(content: string): string[] {
  const match = content.match(/^---\s*\n([\s\S]*?)\n---/);
  if (!match) return [];
  const fm = match[1]!;

  // Single-line: `sources: ["A.pdf", "B.pdf"]`
  const oneLine = fm.match(/^sources:\s*\[(.*?)\]\s*$/m);
  if (oneLine) {
    return splitListItems(oneLine[1]!);
  }

  // Multi-line block:
  //   sources:
  //     - "A.pdf"
  //     - B.pdf
  const block = fm.match(/^sources:\s*\n((?:\s+-\s+.+\n?)+)/m);
  if (block) {
    return block[1]!
      .split('\n')
      .map((line) => line.match(/^\s+-\s+(.+)$/)?.[1])
      .filter((s): s is string => !!s)
      .map(unquote);
  }

  return [];
}

function splitListItems(inner: string): string[] {
  // Naive split(',') breaks on filenames that contain commas — the
  // Medium PDFs Christian uploads look like "... _ Apr, 2026 _
  // Medium.pdf" and the naive split produced garbage fragments that
  // never resolved to any real Source. Do a quote-aware walk instead:
  // only split on commas that aren't inside a "..." or '...' pair.
  const items: string[] = [];
  let buf = '';
  let quote: '"' | "'" | null = null;
  for (let i = 0; i < inner.length; i++) {
    const ch = inner[i]!;
    if (quote) {
      buf += ch;
      if (ch === quote) quote = null;
      continue;
    }
    if (ch === '"' || ch === "'") {
      quote = ch;
      buf += ch;
      continue;
    }
    if (ch === ',') {
      const t = buf.trim();
      if (t) items.push(t);
      buf = '';
      continue;
    }
    buf += ch;
  }
  const tail = buf.trim();
  if (tail) items.push(tail);
  return items.map(unquote);
}

function unquote(s: string): string {
  const trimmed = s.trim();
  if ((trimmed.startsWith('"') && trimmed.endsWith('"')) || (trimmed.startsWith("'") && trimmed.endsWith("'"))) {
    return trimmed.slice(1, -1).trim();
  }
  return trimmed;
}

/**
 * Resolve a frontmatter filename to a Source document in the given KB. The
 * LLM sometimes writes the filename with a `.pdf` suffix, sometimes
 * without, and case doesn't always match. Match with progressively looser
 * strategies.
 */
async function findSourceByName(
  trail: TrailDatabase,
  tenantId: string,
  kbId: string,
  target: string,
): Promise<SourceDoc | null> {
  const normalised = target.trim();
  if (!normalised) return null;

  // Strategy 1: exact filename match (case-sensitive).
  const exact = await trail.db
    .select({ id: documents.id, filename: documents.filename })
    .from(documents)
    .where(
      and(
        eq(documents.tenantId, tenantId),
        eq(documents.knowledgeBaseId, kbId),
        eq(documents.kind, 'source'),
        eq(documents.filename, normalised),
      ),
    )
    .get();
  if (exact) return exact;

  // Strategy 2: case-insensitive match. SQLite LIKE is case-insensitive by
  // default for ASCII — load the source list once and match in JS so
  // non-ASCII (Ø, Æ, Å) also works.
  const allSources = await trail.db
    .select({ id: documents.id, filename: documents.filename })
    .from(documents)
    .where(
      and(
        eq(documents.tenantId, tenantId),
        eq(documents.knowledgeBaseId, kbId),
        eq(documents.kind, 'source'),
      ),
    )
    .all();

  const needle = normalised.toLowerCase();
  const caseHit = allSources.find((s) => s.filename.toLowerCase() === needle);
  if (caseHit) return caseHit;

  // Strategy 3: stem match ignoring extension.
  const stem = stripExt(needle);
  return allSources.find((s) => stripExt(s.filename.toLowerCase()) === stem) ?? null;
}

function stripExt(filename: string): string {
  return filename.replace(/\.[a-z0-9]+$/i, '');
}

async function insertRef(
  trail: TrailDatabase,
  wikiDoc: WikiDoc,
  source: SourceDoc,
): Promise<boolean> {
  const id = `ref_${crypto.randomUUID().slice(0, 12)}`;
  try {
    await trail.db
      .insert(documentReferences)
      .values({
        id,
        tenantId: wikiDoc.tenantId,
        knowledgeBaseId: wikiDoc.knowledgeBaseId,
        wikiDocumentId: wikiDoc.id,
        sourceDocumentId: source.id,
        claimAnchor: null,
      })
      .run();
    return true;
  } catch {
    // Unique-index violation when the same (wikiDoc, source, null) triple
    // already exists — idempotent re-run is expected and silent.
    return false;
  }
}

/**
 * Extract refs for a single Neuron. Safe to call repeatedly. Returns the
 * count of NEW rows actually written (existing ones skip via unique index).
 */
export async function extractReferencesForDoc(
  trail: TrailDatabase,
  docId: string,
): Promise<number> {
  const doc = await trail.db
    .select({
      id: documents.id,
      tenantId: documents.tenantId,
      knowledgeBaseId: documents.knowledgeBaseId,
      filename: documents.filename,
      content: documents.content,
      kind: documents.kind,
      archived: documents.archived,
    })
    .from(documents)
    .where(eq(documents.id, docId))
    .get();

  if (!doc || doc.kind !== 'wiki' || doc.archived || !doc.content) return 0;

  const candidates = parseFrontmatterSources(doc.content);
  if (candidates.length === 0) return 0;

  let inserted = 0;
  for (const name of candidates) {
    const source = await findSourceByName(trail, doc.tenantId, doc.knowledgeBaseId, name);
    if (!source) continue;
    const ok = await insertRef(trail, doc, source);
    if (ok) inserted += 1;
  }
  return inserted;
}

/**
 * Scan every wiki Neuron in a specific KB and populate refs. Used as a
 * targeted post-ingest sweep when a source doc has just been compiled.
 * Idempotent — existing refs skip via unique index.
 */
async function backfillReferencesForKb(
  trail: TrailDatabase,
  kbId: string,
): Promise<number> {
  const wikiDocs = await trail.db
    .select({ id: documents.id })
    .from(documents)
    .where(and(eq(documents.kind, 'wiki'), eq(documents.archived, false), eq(documents.knowledgeBaseId, kbId)))
    .all();

  let total = 0;
  for (const d of wikiDocs) {
    total += await extractReferencesForDoc(trail, d.id);
  }
  return total;
}

/**
 * Boot-time backfill: scan every wiki Neuron in every KB and populate refs.
 * Idempotent — safe to re-run on every restart. Logs a summary when it
 * touches anything, silent otherwise.
 */
export async function backfillReferences(trail: TrailDatabase): Promise<void> {
  const wikiDocs = await trail.db
    .select({ id: documents.id })
    .from(documents)
    .where(and(eq(documents.kind, 'wiki'), eq(documents.archived, false)))
    .all();

  let totalInserted = 0;
  let touched = 0;
  for (const d of wikiDocs) {
    const n = await extractReferencesForDoc(trail, d.id);
    if (n > 0) {
      totalInserted += n;
      touched += 1;
    }
  }
  if (totalInserted > 0) {
    console.log(
      `  reference backfill: ${totalInserted} ref${totalInserted === 1 ? '' : 's'} written across ${touched} Neuron${touched === 1 ? '' : 's'}`,
    );
  }
}

/**
 * Start the live subscriber. Re-extracts refs for a Neuron whenever it
 * commits via the queue. Returns an unsubscribe function for graceful
 * shutdown.
 */
export function startReferenceExtractor(trail: TrailDatabase): () => void {
  const unsubscribe = broadcaster.subscribe((event) => {
    if (event.type === 'candidate_approved') {
      runForDoc(trail, event.documentId).catch((err) => {
        console.error('[reference-extractor] error:', err);
      });
    } else if (event.type === 'ingest_completed') {
      // Two cases depending on which path fired ingest:
      //
      // Queue path (web clipper, external-feed): docId IS the wiki doc.
      // The wiki doc was created with raw candidate content, then ingest
      // rewrote it with compiled frontmatter (sources: [...]). Running
      // extractReferencesForDoc on it now finds the frontmatter and
      // creates the ref.
      //
      // Upload path (re-ingest of a source file): docId IS the source doc.
      // extractReferencesForDoc returns 0 immediately (kind != 'wiki').
      // Fall back to a KB-scoped backfill that scans all wiki docs in the
      // same KB — any that have `sources: ["<this_filename>"]` get a ref.
      runForDocOrKb(trail, event.docId, event.kbId).catch((err) => {
        console.error('[reference-extractor] error:', err);
      });
    }
  });
  console.log('  reference-extractor: listening');
  return unsubscribe;
}

async function runForDoc(trail: TrailDatabase, docId: string | null | undefined): Promise<void> {
  if (!docId) return;
  const inserted = await extractReferencesForDoc(trail, docId);
  if (inserted > 0) {
    console.log(`[reference-extractor] ${docId.slice(0, 8)}…: +${inserted} ref${inserted === 1 ? '' : 's'}`);
  }
}

async function runForDocOrKb(
  trail: TrailDatabase,
  docId: string,
  kbId: string,
): Promise<void> {
  const direct = await extractReferencesForDoc(trail, docId);
  if (direct > 0) {
    console.log(`[reference-extractor] ${docId.slice(0, 8)}…: +${direct} ref${direct === 1 ? '' : 's'}`);
    return;
  }
  // docId was a source doc (upload path) — sweep the KB
  const kbInserted = await backfillReferencesForKb(trail, kbId);
  if (kbInserted > 0) {
    console.log(`[reference-extractor] kb ${kbId.slice(0, 8)}… post-ingest sweep: +${kbInserted} ref${kbInserted === 1 ? '' : 's'}`);
  }
}
